# Generated by Django 4.1.6 on 2023-05-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timechoices",
            name="choice",
            field=models.CharField(max_length=10),
        ),
    ]
