# Generated by Django 4.1.6 on 2023-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_user_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_organizer",
            field=models.BooleanField(default=False),
        ),
    ]
