# Generated by Django 4.1.6 on 2023-05-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_customer_organization_alter_timechoices_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default="Pending",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.status",
            ),
        ),
    ]
