# Generated by Django 4.1.6 on 2023-05-30 11:55

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=sales.models.get_default_status,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.status",
            ),
        ),
    ]
